Bug 1905115: Restart libvirt to detect we are using firewalld
CI is currently failing with error below. This is a new problem, but
seems to be because libvirt is trying to use iptables since it was
started before firewalld. Moving the 02 stuff around to make sure we
always restart libvirtd after firewalld.

```
Executing: /usr/lib/systemd/systemd-sysv-install enable network
+(./02_configure_host.sh:168): main(): '[' y == y ']'
+(./02_configure_host.sh:169): main(): sudo virsh net-destroy ostestbm
Network ostestbm destroyed
+(./02_configure_host.sh:170): main(): sudo virsh net-start ostestbm
error: Failed to start network ostestbm
error: internal error: Failed to apply firewall rules /usr/sbin/iptables
-w --table filter --insert LIBVIRT_INP --in-interface ostestbm
--protocol tcp --destination-port 67 --jump ACCEPT: iptables: No
chain/target/match by that name.
```