mdns-publisher-worker: use the correct template in render-config initContainer
The template for the worker is called worker-config.template. The
python script will fail with

    IOError: [Errno 2] No such file or directory: '/etc/kubernetes/static-pod-resources/config.template'

because config.template does not exist (only on masters).