Mirror manifest lists and use authfile explicitly (#1592)
We have observed that in specific environments (e.g. CI with IPv6-only)
there are missing default credentials for the local registry hosted at
`virthost.ostest.test.metalkube.org:5000` what causes errors like

```
Trying to pull [...]
Error: initializing source docker://virthost.ostest.test [...]
[...] /localimages/local-release-image: authentication required
```

In order to fix that, we are trying to explicitly pull the image with
`--authfile` so that the subsequent `podman run` has the image already
available.

---

We have also noticed that when release image constains manifest list but
the list contains only a single image, then `oc adm release mirror`
unpacks the list causing digests of the images to change. In order to
prevent that, we are explicitly requesting that manifest lists are kept
without unpacking.

This should solve the problem of inconsistency between results returned
by `oc adm release info` and `oc adm release mirror`.