Workaround error with podman when XDG_RUNTIME_DIR is set
On EL8 and podman, you get an error like this:

```
sudo -E podman pull --authfile combined-pullsecret--l08EkMYeFz registry.svc.ci.openshift.org/ocp/release:4.4.0-0.ci-2020-01-23-160905
Error: could not get runtime: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage: permission denied
```

This is due to XDG_RUNTIME_DIR variable being set, and us copying the
user's environment with sudo -E. This is fixed in podman 1.4.4 or later,
however RHEL8 is only at 1.4.2 and it doesn't look like the fix has
been backported, at least as of 1.4.2-6.